### ISSUE TITLE
برطرف نشدن خطای Internal Server Error با وجود آپدیت از طریق Command

### ISSUE THREAD

**Issue by sinatlm** [hiddify/Hiddify-Server#1145]
سلام 
بعد آپدیت خودکار پنل نمایش داده نمی شود و خطای Internal Server Error  میدهد. با اجرای دستور sudo bash update.sh خطاهای زیر نمایش داده می شود:
root@Ubuntu-Hidify:/opt/hiddify-config# sudo bash update.sh
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/sqltypes.py", line 1651, in _object_value_for_elem
    return self._object_lookup[elem]
KeyError: 'sub_link_only'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "<frozen __main__>", line 3, in <module>
  File "<frozen hiddifypanel.__main__>", line 13, in <module>
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 567, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 523, in get_command
    return info.load_app().cli.get_command(ctx, name)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 362, in load_app
    app = self.create_app()
  File "<frozen hiddifypanel.base>", line 79, in create_app_wsgi
  File "<frozen hiddifypanel.base>", line 31, in create_app
  File "<frozen hiddifypanel.panel.init_db>", line 45, in init_db
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 1476, in all
    return self._allrows()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 401, in _allrows
    rows = self._fetchall_impl()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 1389, in _fetchall_impl
    return self._real_result._fetchall_impl()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 1813, in _fetchall_impl
    return list(self.iterator)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/loading.py", line 147, in chunks
    fetch = cursor._raw_all_rows()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 393, in _raw_all_rows
    return [make_row(row) for row in rows]
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 393, in <listcomp>
    return [make_row(row) for row in rows]
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/sqltypes.py", line 1770, in process
    value = self._object_value_for_elem(value)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/sqltypes.py", line 1653, in _object_value_for_elem
    util.raise_(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
LookupError: 'sub_link_only' is not among the defined enum values. Enum name: domaintype. Possible values: direct, cdn, auto_cdn_ip, ..., fake
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/sqltypes.py", line 1651, in _object_value_for_elem
    return self._object_lookup[elem]
KeyError: 'sub_link_only'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "<frozen __main__>", line 3, in <module>
  File "<frozen hiddifypanel.__main__>", line 13, in <module>
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 567, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 523, in get_command
    return info.load_app().cli.get_command(ctx, name)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 362, in load_app
    app = self.create_app()
  File "<frozen hiddifypanel.base>", line 79, in create_app_wsgi
  File "<frozen hiddifypanel.base>", line 31, in create_app
  File "<frozen hiddifypanel.panel.init_db>", line 45, in init_db
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 1476, in all
    return self._allrows()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 401, in _allrows
    rows = self._fetchall_impl()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 1389, in _fetchall_impl
    return self._real_result._fetchall_impl()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 1813, in _fetchall_impl
    return list(self.iterator)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/loading.py", line 147, in chunks
    fetch = cursor._raw_all_rows()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 393, in _raw_all_rows
    return [make_row(row) for row in rows]
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 393, in <listcomp>
    return [make_row(row) for row in rows]
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/sqltypes.py", line 1770, in process
    value = self._object_value_for_elem(value)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/sqltypes.py", line 1653, in _object_value_for_elem
    util.raise_(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
LookupError: 'sub_link_only' is not among the defined enum values. Enum name: domaintype. Possible values: direct, cdn, auto_cdn_ip, ..., fake
hiddify panel version current=6.5.4 latest=6.5.4
Current Config Version=9.4.3 -- Latest=9.4.3
---------------------Finished!------------------------
root@Ubuntu-Hidify:/opt/hiddify-config# sudo bash update.sh
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/sqltypes.py", line 1651, in _object_value_for_elem
    return self._object_lookup[elem]
KeyError: 'sub_link_only'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "<frozen __main__>", line 3, in <module>
  File "<frozen hiddifypanel.__main__>", line 13, in <module>
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 567, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 523, in get_command
    return info.load_app().cli.get_command(ctx, name)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 362, in load_app
    app = self.create_app()
  File "<frozen hiddifypanel.base>", line 79, in create_app_wsgi
  File "<frozen hiddifypanel.base>", line 31, in create_app
  File "<frozen hiddifypanel.panel.init_db>", line 45, in init_db
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 1476, in all
    return self._allrows()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 401, in _allrows
    rows = self._fetchall_impl()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 1389, in _fetchall_impl
    return self._real_result._fetchall_impl()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 1813, in _fetchall_impl
    return list(self.iterator)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/loading.py", line 147, in chunks
    fetch = cursor._raw_all_rows()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 393, in _raw_all_rows
    return [make_row(row) for row in rows]
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 393, in <listcomp>
    return [make_row(row) for row in rows]
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/sqltypes.py", line 1770, in process
    value = self._object_value_for_elem(value)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/sqltypes.py", line 1653, in _object_value_for_elem
    util.raise_(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
LookupError: 'sub_link_only' is not among the defined enum values. Enum name: domaintype. Possible values: direct, cdn, auto_cdn_ip, ..., fake
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/sqltypes.py", line 1651, in _object_value_for_elem
    return self._object_lookup[elem]
KeyError: 'sub_link_only'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "<frozen __main__>", line 3, in <module>
  File "<frozen hiddifypanel.__main__>", line 13, in <module>
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 567, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 523, in get_command
    return info.load_app().cli.get_command(ctx, name)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 362, in load_app
    app = self.create_app()
  File "<frozen hiddifypanel.base>", line 79, in create_app_wsgi
  File "<frozen hiddifypanel.base>", line 31, in create_app
  File "<frozen hiddifypanel.panel.init_db>", line 45, in init_db
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 1476, in all
    return self._allrows()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 401, in _allrows
    rows = self._fetchall_impl()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 1389, in _fetchall_impl
    return self._real_result._fetchall_impl()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 1813, in _fetchall_impl
    return list(self.iterator)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/loading.py", line 147, in chunks
    fetch = cursor._raw_all_rows()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 393, in _raw_all_rows
    return [make_row(row) for row in rows]
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 393, in <listcomp>
    return [make_row(row) for row in rows]
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/sqltypes.py", line 1770, in process
    value = self._object_value_for_elem(value)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/sqltypes.py", line 1653, in _object_value_for_elem
    util.raise_(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
LookupError: 'sub_link_only' is not among the defined enum values. Enum name: domaintype. Possible values: direct, cdn, auto_cdn_ip, ..., fake
hiddify panel version current=6.5.4 latest=6.5.4
Current Config Version=9.4.3 -- Latest=9.4.3
---------------------Finished!------------------------
root@Ubuntu-Hidify:/opt/hiddify-config# 

ضمنا با وجود عدم نمایش پنل ، کلاینتها بدون مشکل وصل هستند

**Comment by vafaaee** [comment]
این مشکل رو در آپدیت از نسخه بتا به ریلیز برخوردم
و برای reinstall هم همین ارور رو میده



2023-05-22 17:23:10 (103 MB/s) - ‘GeoLite2-Country.mmdb’ saved [5916445/5916445]

/usr/local/bin/yt-dlp
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/sqltypes.py", line 1651, in _object_value_for_elem
    return self._object_lookup[elem]
KeyError: 'sub_link_only'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "<frozen main>", line 3, in <module>
  File "<frozen hiddifypanel.main>", line 13, in <module>
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in call
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 567, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 523, in get_command
    return info.load_app().cli.get_command(ctx, name)
  File "/usr/local/lib/python3.10/dist-packages/flask/cli.py", line 362, in load_app
    app = self.create_app()
  File "<frozen hiddifypanel.base>", line 79, in create_app_wsgi
  File "<frozen hiddifypanel.base>", line 31, in create_app
  File "<frozen hiddifypanel.panel.init_db>", line 45, in init_db
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 1476, in all
    return self._allrows()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 401, in _allrows
    rows = self._fetchall_impl()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 1389, in _fetchall_impl
    return self._real_result._fetchall_impl()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 1813, in _fetchall_impl
    return list(self.iterator)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/orm/loading.py", line 147, in chunks
    fetch = cursor._raw_all_rows()
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 393, in _raw_all_rows
    return [make_row(row) for row in rows]
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/result.py", line 393, in <listcomp>
    return [make_row(row) for row in rows]
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/sqltypes.py", line 1770, in process
    value = self._object_value_for_elem(value)
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/sql/sqltypes.py", line 1653, in _object_value_for_elem
    util.raise_(
  File "/usr/local/lib/python3.10/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
LookupError: 'sub_link_only' is not among the defined enum values. Enum name: domaintype. Possible values: direct, cdn, auto_cdn_ip, ..., fake
Exception in Hiddify Panel. Please send the log to [hiddify@gmail.com](mailto:hiddify@gmail.com)
Press any key to return to menu

**Comment by sinatlm** [comment]
مشکل توسط یکی از دوستان عزیر برطرف شد. 
با دانگرید برنامه به ورژن  قبلی  از طریف منوی  Hidiffy در SSH ، پنل برنامه برگشت.

**Comment by hiddify-com** [comment]
Thank you for your contribution. However, due to many similar or old issues, this bot automatically closed the issue. Please open a new issue if the problem is still there.

این یک پیام خودکار است.
به علت شباهت های بسایری که بین ایشو ها بود و خیلی هاش رفع شده
برای مدیریت بهتر به صورت خودکار تمام ایشو ها بسته میشه

ولی خواهشمند است که در صورتی که همچنان مشکل شما وجود دارد و یا نیاز به بهبود هست به ما پیام بدید

تا بتونیم مدیریت بهتری روی ایشو ها داشته باشیم.

با سپاس
