### ISSUE TITLE
Not working after update...

### ISSUE THREAD

**Issue by omer83** [hiddify/Hiddify-Server#2113]
Hello,

I updated our panel Hiddify Panel 7.0.0 but it's doesnt work anymore.

```
500
Oops! something went wrong. Hiddify Panel 7.0.0
Please contact info@hiddify.com with the details in this page

        
list object has no element 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "<frozen hiddifypanel.panel.admin.Dashboard>", line 78, in index
  File "/usr/local/lib/python3.10/dist-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/usr/local/lib/python3.10/dist-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/templates/index.html", line 1, in top-level template code
    {% extends 'admin-layout.html' %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/admin-layout.html", line 2, in top-level template code
    {% from 'macros.html' import icon,render_nav_item %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/master.html", line 76, in top-level template code
    {% block page_body %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/master.html", line 108, in block 'page_body'
    {% block body %}{% endblock %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/templates/index.html", line 118, in block 'body'
    {{info_box("cpu","fa-solid fa-microchip", _("CPU %(cores)s Cores", cores=stats['system']['num_cpus']),
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 466, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: list object has no element 1
```

**Comment by hiddify-com** [comment]
Thank you for your contribution. However, due to many similar or old issues, this bot automatically closed the issue. Please open a new issue if the problem is still there.

این یک پیام خودکار است.
به علت شباهت های بسایری که بین ایشو ها بود و خیلی هاش رفع شده
برای مدیریت بهتر به صورت خودکار تمام ایشو ها بسته میشه

ولی خواهشمند است که در صورتی که همچنان مشکل شما وجود دارد و یا نیاز به بهبود هست به ما پیام بدید

تا بتونیم مدیریت بهتری روی ایشو ها داشته باشیم.

با سپاس
