### ISSUE TITLE
گزینه ریستارت سیستم کار نمی کند.

### ISSUE THREAD

**Issue by mbm13781221** [hiddify/Hiddify-Server#3058]
500
خطایی رخ داده است!! Hiddify Panel 7.1.2
لطفا با هیدیفای از طریق آدرس ایمیل info@hiddify.com و ذکر مشخصات این صفحه در ارتباط باشید.

        
'module' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "<frozen hiddifypanel.panel.admin.Actions>", line 71, in reset
  File "<frozen hiddifypanel.panel.hiddify>", line 67, in wrapper
  File "<frozen hiddifypanel.panel.admin.Actions>", line 91, in reset2
TypeError: 'module' object is not subscriptable

**Comment by Mstrman4** [comment]
اره داداش منم الان دیدم تازه کانفیگ ها هم از کار افتادن💔

**Comment by hiddify-com** [comment]
Thank you for your contribution. However, due to many similar or old issues, this bot automatically closed the issue. Please open a new issue if the problem is still there.

این یک پیام خودکار است.
به علت شباهت های بسایری که بین ایشو ها بود و خیلی هاش رفع شده
برای مدیریت بهتر به صورت خودکار تمام ایشو ها بسته میشه

ولی خواهشمند است که در صورتی که همچنان مشکل شما وجود دارد و یا نیاز به بهبود هست به ما پیام بدید

تا بتونیم مدیریت بهتری روی ایشو ها داشته باشیم.

با سپاس
