### ISSUE TITLE
ساخت دامنه ریلیتی با مشکل اررور 500 سرور مواجه میشود

### ISSUE THREAD

**Issue by sbahrami-vz** [hiddify/Hiddify-Server#3080]
**Describe the bug**
به محض اینکه دامنه ریلیتی رو میخوام ثبت کنم سرور ارور 500 میده
**To Reproduce**
پانل ورژن جدید رو روی سرور جدید نصب کنید، به قسمت ثبت دامنه برید، ریلیتی رو انتخاب کنید، نام دامنه و نام سرور ریلیتی رو وارد کنید من از تلوبیون استفاده کردم اول بعد از لیست پیشنهادی استفاده کردم. اجبار به استفاده از آی پی زیر: یا دامنه آی پی تمیز یا خالی یا از لیست پیشنهادی انتخاب کنید.
من خودم از ساب دامین مستقیم روی آی پی سرور استفاده کردم (دی ان اس منیجمنت روی کلود فلیره ولی پروکسی فعال نیست)

**Expected behavior**
باید ثبت بشه دامنه و مشکلی پیش نیاد
**Screenshots**
![image](https://github.com/hiddify/hiddify-config/assets/121781966/a3667da5-1f5a-42f7-96d5-52ebc9c9e3e8)

![image](https://github.com/hiddify/hiddify-config/assets/121781966/da62c3da-a6ba-4fb3-b688-5adeedb06f18)

**Desktop (please complete the following information):**
 - OS: ویندوز
 - Browser کروم، بریو، اج، موزیلا

**Smartphone (please complete the following information):**
 - Device: سامسونگ
 - OS: اندروید 13

**Additional context**
500
خطایی رخ داده است!! Hiddify Panel 7.1.3
لطفا با هیدیفای از طریق آدرس ایمیل info@hiddify.com و ذکر مشخصات این صفحه در ارتباط باشید.

        
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_admin/model/base.py", line 2088, in create_view
    model = self.create_model(form)
  File "/usr/local/lib/python3.8/dist-packages/flask_admin/contrib/sqla/view.py", line 1165, in create_model
    if not self.handle_view_exception(ex):
  File "/usr/local/lib/python3.8/dist-packages/flask_admin/contrib/sqla/view.py", line 1133, in handle_view_exception
    return super(ModelView, self).handle_view_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/flask_admin/contrib/sqla/view.py", line 1162, in create_model
    self._on_model_change(form, model, True)
  File "/usr/local/lib/python3.8/dist-packages/flask_admin/model/base.py", line 1569, in _on_model_change
    self.on_model_change(form, model, is_created)
  File "<frozen hiddifypanel.panel.admin.DomainAdmin>", line 230, in on_model_change
  File "<frozen hiddifypanel.panel.hiddify3>", line 223, in debug_flash_if_not_in_the_same_asn
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by hiddify-com** [comment]
Thank you for your contribution. However, due to many similar or old issues, this bot automatically closed the issue. Please open a new issue if the problem is still there.

این یک پیام خودکار است.
به علت شباهت های بسایری که بین ایشو ها بود و خیلی هاش رفع شده
برای مدیریت بهتر به صورت خودکار تمام ایشو ها بسته میشه

ولی خواهشمند است که در صورتی که همچنان مشکل شما وجود دارد و یا نیاز به بهبود هست به ما پیام بدید

تا بتونیم مدیریت بهتری روی ایشو ها داشته باشیم.

با سپاس
