### ISSUE TITLE
مشکل در نمایش لینک های کاربران داخل پنل

### ISSUE THREAD

**Issue by nima2010** [hiddify/Hiddify-Server#3121]
سلام وقت بخیر
داخل پنل وقتی میخوام وارد لینک کاربر بشم به این خطا میخورم، یوزر جدید هم اگر بسازم باز همینه و یوزرهای قدیمی هم مشکل نمایش لینک دارن.
با reinstall هم مشکلم حل نشده.
`500
خطایی رخ داده است!! Hiddify Panel 7.1.3
لطفا با هیدیفای از طریق آدرس ایمیل info@hiddify.com و ذکر مشخصات این صفحه در ارتباط باشید.

        
The MaxMind DB file's data section contains bad data (unknown data type or corrupt data)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "<frozen hiddifypanel.panel.user.user>", line 43, in new
  File "<frozen hiddifypanel.panel.user.user>", line 259, in get_common_data
  File "<frozen hiddifypanel.panel.clean_ip>", line 73, in get_real_user_ip_debug
  File "/usr/local/lib/python3.10/dist-packages/maxminddb/reader.py", line 120, in get
    (record, _) = self.get_with_prefix_len(ip_address)
  File "/usr/local/lib/python3.10/dist-packages/maxminddb/reader.py", line 151, in get_with_prefix_len
    return self._resolve_data_pointer(pointer), prefix_len
  File "/usr/local/lib/python3.10/dist-packages/maxminddb/reader.py", line 218, in _resolve_data_pointer
    (data, _) = self._decoder.decode(resolved)
  File "/usr/local/lib/python3.10/dist-packages/maxminddb/decoder.py", line 162, in decode
    return decoder(self, size, new_offset)
  File "/usr/local/lib/python3.10/dist-packages/maxminddb/decoder.py", line 61, in _decode_double
    self._verify_size(size, 8)
  File "/usr/local/lib/python3.10/dist-packages/maxminddb/decoder.py", line 177, in _verify_size
    raise InvalidDatabaseError(
maxminddb.errors.InvalidDatabaseError: The MaxMind DB file's data section contains bad data (unknown data type or corrupt data)
`

<img width="717" alt="hiddify-error" src="https://github.com/hiddify/hiddify-config/assets/6032182/f83bf619-bca6-4f62-9e89-109f1541f408">

**Comment by hiddify-com** [comment]
Thank you for your contribution. However, due to many similar or old issues, this bot automatically closed the issue. Please open a new issue if the problem is still there.

این یک پیام خودکار است.
به علت شباهت های بسایری که بین ایشو ها بود و خیلی هاش رفع شده
برای مدیریت بهتر به صورت خودکار تمام ایشو ها بسته میشه

ولی خواهشمند است که در صورتی که همچنان مشکل شما وجود دارد و یا نیاز به بهبود هست به ما پیام بدید

تا بتونیم مدیریت بهتری روی ایشو ها داشته باشیم.

با سپاس
