### ISSUE TITLE
internal server error 

### ISSUE THREAD

**Issue by amin1363** [hiddify/Hiddify-Server#3192]
متاسفانه از امروز صبح با پیام 
internal server error
مواجه شدم و پس از تلاش جهت آپدیت یا نصب مجدد از طریق ssh موقع آپدیت با پیام
Exception in Hiddify Panel
و بعد 
LookupError: 'ssh_server_enable' is not among the defined enum values. Enum name: configenum. Possible values: first_setup, core_type, warp_enable,
..., path_grpc
مواجه شدم

**Comment by SRNOURI** [comment]
متاسفانه من هم از امروز همین مشکل رو دارم و به پنل دسترسی ندارم.

**Comment by amir-ardalanuk** [comment]
Console Error 
```log
Aug 05 01:59:27 ubuntu-2gb-fsn1-1 systemd[1]: Starting hiddify panel...
Aug 05 01:59:27 ubuntu-2gb-fsn1-1 systemd[1]: Started hiddify panel.
 * Reloading configuration files for periodic command scheduler cron
   ...done.
/usr/local/bin/yt-dlp
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/__main__.py", line 13, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 567, in main
    return super().main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1651, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1698, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 523, in get_command
    return info.load_app().cli.get_command(ctx, name)
  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 362, in load_app
    app = self.create_app()
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/base.py", line 81, in create_app_wsgi
    app = create_app()
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/base.py", line 30, in create_app
    init_db()
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/panel/init_db.py", line 101, in init_db
    db_action()
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/panel/init_db.py", line 116, in _v49
    priv, publ = hiddify.get_ed25519_private_public_pair()
  File "/usr/local/lib/python3.8/dist-packages/hiddifypanel/panel/hiddify.py", line 701, in get_ed25519_private_public_pair
    format=serialization.PrivateFormat.OpenSSH,
  File "/usr/lib/python3.8/enum.py", line 384, in __getattr__
    raise AttributeError(name) from None
AttributeError: OpenSSH
Exception in Hiddify Panel. Please send the log to hiddify@gmail.com
```log

**Comment by hiddify-com** [comment]
Thank you for your contribution. However, due to many similar or old issues, this bot automatically closed the issue. Please open a new issue if the problem is still there.

این یک پیام خودکار است.
به علت شباهت های بسایری که بین ایشو ها بود و خیلی هاش رفع شده
برای مدیریت بهتر به صورت خودکار تمام ایشو ها بسته میشه

ولی خواهشمند است که در صورتی که همچنان مشکل شما وجود دارد و یا نیاز به بهبود هست به ما پیام بدید

تا بتونیم مدیریت بهتری روی ایشو ها داشته باشیم.

با سپاس
