### ISSUE TITLE
500 error after fresh install

### ISSUE THREAD

**Issue by miladmeidanshahi** [hiddify/Hiddify-Server#3322]
Hi,
after fresh installation i got error for `quick setup` route.
```
500
Oops! something went wrong. Hiddify Panel 8.6.7
Please contact info@hiddify.com with the details in this page

        
too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/QuickSetup.py", line 28, in index
    return render_template('quick_setup.html', lang_form=get_lang_form(), form=get_quick_setup_form(), ipv4=hiddify.get_ip(4), ipv6=hiddify.get_ip(6), admin_link=admin_link(), show_domain_info=True)
  File "/usr/local/lib/python3.10/dist-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/usr/local/lib/python3.10/dist-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/templates/quick_setup.html", line 32, in top-level template code
    <a href="#" data-copy="{{ip}}" class="btn btn-primary copy-link">{{ip}}</a>
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/admin-layout.html", line 2, in top-level template code
    {% from 'macros.html' import icon,render_nav_item %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/master.html", line 76, in top-level template code
    {% block page_body %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/templates/master.html", line 108, in block 'page_body'
    {% block body %}{% endblock %}
  File "/usr/local/lib/python3.10/dist-packages/hiddifypanel/panel/admin/templates/quick_setup.html", line 53, in block 'body'
    {{render_form(lang_form)}}
  File "/usr/local/lib/python3.10/dist-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/usr/local/lib/python3.10/dist-packages/flask_bootstrap/templates/bootstrap4/form.html", line 303, in template
    {{ render_field(field,
  File "/usr/local/lib/python3.10/dist-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/usr/local/lib/python3.10/dist-packages/flask_bootstrap/templates/bootstrap4/form.html", line 224, in template
    {{ field(class="form-control%s" % extra_classes, **kwargs)|safe }}
  File "/usr/local/lib/python3.10/dist-packages/wtforms/fields/core.py", line 172, in __call__
    return self.meta.render_field(self, kwargs)
  File "/usr/local/lib/python3.10/dist-packages/wtforms/meta.py", line 64, in render_field
    return field.widget(field, **render_kw)
  File "/usr/local/lib/python3.10/dist-packages/wtforms/widgets/core.py", line 351, in __call__
    for val, label, selected in field.iter_choices():
  File "/usr/local/lib/python3.10/dist-packages/wtforms/fields/choices.py", line 115, in _choices_generator
    for value, label in _choices:
ValueError: too many values to unpack (expected 2)
```

![Screenshot from 2023-10-12 16-08-56](https://github.com/hiddify/Hiddify-Server/assets/11172818/ed86700a-b652-4809-adc1-d288d41da07e)

**Server (please complete the following information):**
 - OS: Linux ubuntu 22 lts
 - Browser chrome

**Comment by ramindoroozeh** [comment]
I have the same problem

**Comment by saveiran2023** [comment]
mine is same

**Comment by ThihaWin177** [comment]
I have the same problem
<img width="625" alt="Screenshot 2024-06-20 110805" src="https://github.com/hiddify/Hiddify-Manager/assets/159916323/efe999bf-0486-4625-b5ff-9a6244eaaa23">
