### ISSUE TITLE
خطا در ثبت دامنه بعد از نصب

### ISSUE THREAD

**Issue by mostafamvh** [hiddify/Hiddify-Server#693]
سلام اول که مرسی بابت تموم زحماتتون توی این مدت
من جدیدا اومدم پنل رو یه سرور جدید نصب کنم، بعد از نصب وارد پنل که میشم تا دامنه رو ست کنم با این خطا مواجه میشم:

500
خطایی رخ داده است!! Hiddify Panel 3.1.10

name 'get_child' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "<frozen hiddifypanel.panel.admin.QuickSetup>", line 52, in post
  File "<frozen hiddifypanel.panel.hiddify2>", line 125, in bulk_register_configs
NameError: name 'get_child' is not defined

**Comment by hiddify-com** [comment]
Thank you for your contribution. However, due to many similar or old issues, this bot automatically closed the issue. Please open a new issue if the problem is still there.

این یک پیام خودکار است.
به علت شباهت های بسایری که بین ایشو ها بود و خیلی هاش رفع شده
برای مدیریت بهتر به صورت خودکار تمام ایشو ها بسته میشه

ولی خواهشمند است که در صورتی که همچنان مشکل شما وجود دارد و یا نیاز به بهبود هست به ما پیام بدید

تا بتونیم مدیریت بهتری روی ایشو ها داشته باشیم.

با سپاس
