### ISSUE TITLE
دکمه ریستارت سیستم

### ISSUE THREAD

**Issue by realartin** [hiddify/Hiddify-Server#733]
![Screenshot_2023-04-20-14-03-55-217_com.android.chrome.jpg](https://user-images.githubusercontent.com/52799129/233341046-38a68657-a8f1-4c84-9260-9425caea46c3.jpg)
500

خطایی رخ داده است!! Hiddify Panel 4.1.2

لطفا با هیدیفای از طریق آدرس ایمیل hiddify@gmail.com و ذکر مشخصات این صفحه در ارتباط باشید.

[Errno 2] No such file or directory: "echo 'reboot'|at now + 3s " Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request rv = self.dispatch_request() File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args) File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 268, in proxy response = view(**request.view_args) File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 239, in inner return fn(*args, **kwargs) File "<frozen hiddifypanel.panel.admin.Actions>", line 63, in reset File "<frozen hiddifypanel.panel.hiddify>", line 67, in wrapper File "<frozen hiddifypanel.panel.admin.Actions>", line 69, in reset2 File "/usr/lib/python3.10/subprocess.py", line 969, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) FileNotFoundError: [Errno 2] No such file or directory: "echo 'reboot'|at now + 3s "

**Comment by realartin** [comment]
بعد از کلیک روی دکمه ریستارت سیستم این ارور رو میده اخرین ورژن هستم

**Comment by hiddify-com** [comment]
Thank you for your contribution. However, due to many similar or old issues, this bot automatically closed the issue. Please open a new issue if the problem is still there.

این یک پیام خودکار است.
به علت شباهت های بسایری که بین ایشو ها بود و خیلی هاش رفع شده
برای مدیریت بهتر به صورت خودکار تمام ایشو ها بسته میشه

ولی خواهشمند است که در صورتی که همچنان مشکل شما وجود دارد و یا نیاز به بهبود هست به ما پیام بدید

تا بتونیم مدیریت بهتری روی ایشو ها داشته باشیم.

با سپاس
