### ISSUE TITLE
مشکل در لینک سابسکریپشن

### ISSUE THREAD

**Issue by ErfanMajouni** [hiddify/Hiddify-Server#951]
خطایی رخ داده است!! Hiddify Panel 6.2.0
لطفا با هیدیفای از طریق آدرس ایمیل hiddify@gmail.com و ذکر مشخصات این صفحه در ارتباط باشید.

        
do_base_64() missing 1 required positional argument: 'str'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python3.10/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "<frozen hiddifypanel.panel.user.user>", line 106, in all_configs
TypeError: do_base_64() missing 1 required positional argument: 'str'

**Comment by hiddify-com** [comment]
Thank you for your contribution. However, due to many similar or old issues, this bot automatically closed the issue. Please open a new issue if the problem is still there.

این یک پیام خودکار است.
به علت شباهت های بسایری که بین ایشو ها بود و خیلی هاش رفع شده
برای مدیریت بهتر به صورت خودکار تمام ایشو ها بسته میشه

ولی خواهشمند است که در صورتی که همچنان مشکل شما وجود دارد و یا نیاز به بهبود هست به ما پیام بدید

تا بتونیم مدیریت بهتری روی ایشو ها داشته باشیم.

با سپاس
